
***************************************************************************
*                                                                         *
*  Windows NT Change Password Utility / Registry Editor / Boot disk       *
*                                                                         *
*  (c) 1998-2000 Petter Nordahl-Hagen. Distributable under the GNU GPL    *
*  Linux kernel & utilities (c) lots of people, freely distributable      *
*  desLIB crypt routines (c) 1995-1997 Eric Young eay@mincom.oz.au        *
*  NTFS utilities (c) 1995-1997 Martin von Löwis                          *
*  Thanks to EZ for bootfloppystuff                                       *
*                                                                         *
* DISCLAIMER: THIS SOFTWARE COMES WITH ABSOLUTELY NO WARRANTIES!          *
*             THE AUTHOR CAN NOT BE HELD RESPONSIBLE FOR ANY DAMAGE       *
*             CAUSED BY THE (MIS)USE OF THIS SOFTWARE                     *
*                                                                         *
* NOTE: The 'chntpw' binary contains cryptograhic algorithms,             *
*       like DES and others, which may be illegal to re-export            *
*       from your country.                                                *
*                                                                         *
* More info at: http://home.eunet.no/~pnordahl/ntpasswd/                  *
* Email       : pnordahl@eunet.no                                         *
*                                                                         *
***************************************************************************
* Floppy build date:  Wed Jun 7 21:26:14 CEST 2000

